trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo add-apt-repository universe
      sudo apt-get update
      sudo apt-get install libboost1.71-all-dev
      mkdir build
      cd build
      cmake ..
      cmake --build .
      
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build'
      contents: 'ARXML_LanguageServer'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Executable_Linux'