trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo add-apt-repository universe
      sudo apt-get update
      sudo apt-get install libboost1.71-all-dev
      cmake .
      cmake --build .
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. -G"MinGW Makefiles" -DBOOST_ROOT=%BOOST_ROOT_1_72_0%
      mingw32-make.exe