trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo add-apt-repository universe
      sudo apt-get update
      sudo apt-get install libboost1.71-all-dev
      cmake .
      cmake --build .
      
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: jonasrock
      repositoryName: '$(Build.Repository.Name)' 
      action: 'edit'
      tag: CI Release
      assets: $(Build.ArtifactStagingDirectory)/build/*
      isDraft: true


- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. -DBOOST_ROOT=%BOOST_ROOT_1_72_0%
      cmake --build .