trigger:
- master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - script: |
      sudo add-apt-repository universe
      sudo apt-get update
      sudo apt-get install libboost1.71-all-dev
      cmake .
      cmake --build .